[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = "0.6.0"
fraction = "0.15.3"
image = "0.25.5"
indicatif = { version = "0.17.9", features = ["rayon"] }
itertools = "0.13.0"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.1"
